package driver;

import com.jjjwelectronics.Item;
import com.jjjwelectronics.card.Card;
import com.jjjwelectronics.screen.ITouchScreen;
import managers.SystemManager;
import managers.enums.SessionStatus;
import managers.interfaces.IScreen;

import javax.naming.OperationNotSupportedException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;

public class MainScreenForm implements IScreen {
    protected final SystemManagerForm mainView;
    protected JButton startSessionButton;
    protected JLabel welcomeLabel;
    protected JPanel root;
    protected SystemManager sm;
    protected ITouchScreen tch;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(spacer1, gbc);
        startSessionButton = new JButton();
        startSessionButton.setText("Start Session");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(startSessionButton, gbc);
        welcomeLabel = new JLabel();
        welcomeLabel.setText("Welcome to the company!");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        root.add(welcomeLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    public MainScreenForm(SystemManager sm) {
        this.sm = sm;

        // listening for the events emitted from the system manager
        sm.attach(this);

        // creating the system manager form
        mainView = new SystemManagerForm(sm);
    }

    @Override
    public JPanel getPanel() {
        return root;
    }

    @Override
    public JFrame getFrame() {
        throw new UnsupportedOperationException("This object does not have a JFrame");
    }

    @Override
    public void configure(ITouchScreen touchScreen) {
        // saving a reference
        tch = touchScreen;

        // updating the touch screen
        touchScreen.getFrame().setContentPane(root);

        mainView.configure(touchScreen);

        // logic to change views
        startSessionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // switching the main view
                touchScreen.getFrame().setContentPane(mainView.getPanel());
            }
        });
    }

    @Override
    public void notifyItemAdded(Item item) {
        // do nothing with this event
    }

    @Override
    public void notifyItemRemoved(Item item) {
        // do nothing with this event
    }

    @Override
    public void notifyStateChange(SessionStatus state) {
        switch (state) {
            case NORMAL -> {
            }
            case BLOCKED -> {
            }
            case PAID -> {
            }
            case DISABLED -> {
                handleDisabled();
            }
        }
    }

    protected void handleDisabled() {

    }

    @Override
    public void notifyRefresh() {
        // do nothing with this event
    }

    @Override
    public void notifyPaymentAdded(BigDecimal value) {
        // do nothing with this event
    }

    @Override
    public void notifyPaymentWindowClosed() {
        // do nothing with this event
    }

    @Override
    public void notifyInvalidCardRead(Card card) {
        // do nothing with this event
    }
}
