package driver;

import javax.swing.*;
import java.awt.*;

// ItemSearch class for GUI components related to item search
public class ItemSearch {
    
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        // Creating a JPanel named panel1
        final JPanel panel1 = new JPanel();

        // Setting the layout manager for the panel
        // (In this case, it's a GridLayoutManager with 1 row and 1 column)
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
